dataset=../preprocessing/2017
python3 train.py --tok_vocab ${dataset}/tok_vocab\
                --lem_vocab ${dataset}/lem_vocab\
                --pos_vocab  ${dataset}/pos_vocab\
                --ner_vocab ${dataset}/ner_vocab\
                --concept_vocab ${dataset}/concept_vocab\
                --predictable_concept_vocab ${dataset}/predictable_concept_vocab\
                --rel_vocab ${dataset}/rel_vocab\
                --word_char_vocab ${dataset}/word_char_vocab\
                --concept_char_vocab ${dataset}/concept_char_vocab\
                --train_data ${dataset}/train.txt_processed_preprocess \
                --dev_data ${dataset}/dev.txt_processed_preprocess \
                --lexical_mapping ../preprocessing/common/out_stanford \
                --word_char_dim 32\
                --word_dim 200\
                --pos_dim 32\
                --ner_dim 16\
                --concept_char_dim 32\
                --concept_dim 300 \
                --rel_dim 100 \
                --cnn_filter 3 256\
                --char2word_dim 128\
                --char2concept_dim 128\
                --embed_dim 512\
                --ff_embed_dim 1024\
                --num_heads 8\
                --snt_layers 4\
                --graph_layers 1\
                --inference_layers 3\
                --dropout 0.2\
                --unk_rate 0.33\
                --epochs 1000\
                --train_batch_size 6666\
                --dev_batch_size 2222 \
                --lr 1e-3 \
                --warmup_steps 2000\
                --print_every 100 \
                --eval_every 300 \
                --ckpt ckpt\
                --world_size 1\
                --gpus 1\
                --MASTER_ADDR localhost\
                --MASTER_PORT 29505\
                --start_rank 0
